FROM docker.io/alpine:3.18

RUN apk add meson ninja gcompat tzdata msmtp perl curl meson git \
        libc-dev sqlite-dev libconfig-dev curl-dev libmicrohttpd-dev \
        openssl-dev libucontext-dev gcc readline-dev
